name: app_images
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  awesome_dio_interceptor: ^0.0.2+4
  flutter_hooks: ^0.18.5+1
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  dartz: ^0.10.1
  dio: ^4.0.6
  go_router: ^5.1.1
  injectable: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.15
  flutter_svg: ^1.1.6
  flutter_svg_image: ^1.0.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  platform: ^3.1.0
  provider: ^6.0.5
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  injectable_generator: ^2.1.3
  json_serializable: ^6.5.4
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#0077FF"
  image: assets/images/logo_transporte.png
  branding: assets/images/brandingv2.png
  color_dark: "#252A2B"
  image_dark: assets/images/logo_transporte.png
  branding_dark: assets/images/brandingv2.png
  android_disable_fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_app.png"
  min_sdk_android: 21
